Repository kakafajar/websitedonasi, pull requests merged in 2024-12, with the labels that each got.

#20 02desember24irfan
  admin/index.php
  admin/transaksi.php
  admin/views/index.php
  admin/views/modalform.js
  admin/views/modelpembayaran.php
  admin/views/transaksi.php
  admin/views/users.php
  donasi.php
  views/donasi.php
Labels: frontend, backend

#25 11des24irfan
  admin/index.php
  admin/js/datatables-simple-demo.js
  admin/js/index.js
  admin/js/layout.js
  admin/js/modalform.js
  admin/views/index.php
  admin/views/layout.php
  admin/views/modelpembayaran.php
  admin/views/transaksi.php
  admin/views/users.php
  donasi.php
Labels: backend

#26 13des24irfan
  admin/index.php
  admin/js/index.js
  admin/js/layout.js
  admin/js/modalform.js
  admin/views/index.php
  admin/views/transaksi.php
Labels: backend

#27 memperbaiki tombol slider carousel
  admin/views/index.php
  admin/views/layout.php
  mailconfig.php
  views/index.php
  views/layout.php
  views/tentang.php
Labels: frontend, backend

#28 14des24ali
  .gitignore
  donasi.php
  mailconfig.php
  views/css/styles.css
  views/donasi.php
Labels: frontend

#30 menambahkan scrollbar ke kotak konfirmasi
  views/index.php
  views/konfirmasi.php
  views/layout.php
Labels: frontend

#31 pengupdate an phpmailer
  donasi.php
  functions.php
  index.php
  konfirmasi.php
  phpmailer.php
  views/layout.php
Labels: backend

#34 22des24irfan
  admin/js/modalform.js
  admin/modelpembayaran.php
  admin/transaksi.php
  admin/users.php
  admin/views/modelpembayaran.php
  admin/views/transaksi.php
  admin/views/users.php
  models/model.php
  models/transaksi.php
Labels: backend

#35 menuju release (v1.0)
  admin/index.php
  admin/js/modalform.js
  admin/js/transaksi.js
  admin/modelpembayaran.php
  admin/transaksi.php
  admin/users.php
  admin/views/layout.php
  admin/views/modelpembayaran.php
  admin/views/transaksi.php
  admin/views/users.php
  donasi.php
  functions.php
  index.php
  konfirmasi.php
  models/model.php
  models/transaksi.php
  views/donasi.php
  views/emaildata.html
  views/index.php
  views/js/donasi.js
  views/js/index.js
  views/js/konfirmasi.js
  views/konfirmasi.php
Labels: frontend, backend

#36 memfix bug checkbox tidak menset selection baris
  admin/views/modelpembayaran.php
  admin/views/users.php
Labels: backend

#37 28des24irfan
  admin/js/modalform.js
  admin/js/transaksi.js
  admin/modelpembayaran.php
  admin/transaksi.php
  admin/users.php
  admin/views/modelpembayaran.php
  admin/views/transaksi.php
  admin/views/users.php
  donasi.php
  konfirmasi.php
  models/modelpembayaran.php
  views/index.php
  views/konfirmasi.php
Labels: frontend, backend

#38 memfix bug export csv me export semua data yang harusnya me export ya…
  admin/js/transaksi.js
Labels: backend

#39 mengupdate database
  models/donasidb.sql
Labels: backend
