Repository kakafajar/websitedonasi, pull requests merged in 2024-11, with the labels that each got.

#1 test sync
  home.php
Labels: frontend

#2 ganti navbar
  home.php
Labels: frontend

#4 171124fajar
  donasi.php
  home1.php
  img/bg1.jpg
  img/bg2.jpg
  img/bg3.jpg
  img/kegiatan1.jpg
  img/kegiatan2.jpg
  img/kegiatan3.jpg
  img/program.jpg
  img/program2.jpg
  img/program3.jpg
  kegiatan.php
  style.css
  styles.css
  tentang.php
Labels: frontend

#5 18nov24irfan
  admin/css/styles.css
  admin/index.php
  admin/js/datatables-simple-demo.js
  admin/js/scripts.js
  admin/layout.php
  admin/login.php
  admin/logout.php
  admin/models/connection.php
  admin/models/user.php
Labels: frontend, backend

#7 menambahkan semua table di halaman admin
  admin/index.php
  admin/layout.php
  admin/login.php
  admin/modelpembayaran.php
  admin/models/modelpembayaran.php
  admin/models/transaksi.php
  admin/models/user.php
  admin/transaksi.php
  admin/users.php
Labels: backend

#8 Be25nov24irfan
  admin/index.php
  admin/login.php
  admin/modelpembayaran.php
  admin/models/model.php
  admin/models/modelpembayaran.php
  admin/models/transaksi.php
  admin/models/user.php
  admin/transaksi.php
  admin/users.php
  admin/views/index.php
  admin/views/layout.php
  admin/views/login.php
  admin/views/modalform.js
  admin/views/modelpembayaran.php
  admin/views/transaksi.php
  admin/views/users.php
  donasidb.sql
Labels: backend

#10 Fe27jam5.17ali
  img/founder.jpeg
  img/kegiatan13.jpg
  img/kegiatan14.jpg
  img/kegiatan15.jpg
  img/kegiatan16.jpg
  img/kegiatan17.jpg
  img/wanita.jpeg
  index.html
  kegiatan.html
  process.php
  styles.css
  tentang.html
Labels: frontend

#15 28nov24irfan
  admin/login.php
  admin/modelpembayaran.php
  admin/transaksi.php
  admin/users.php
  admin/views/layout.php
  dashboard.php
  donasi.php
  form.php
  index.html
  index.php
  kegiatan.html
  kegiatan.php
  models/connection.php
  models/donasidb.sql
  models/model.php
  models/modelpembayaran.php
  models/transaksi.php
  models/user.php
  process.php
  views/css/styles.css
  views/donasi.php
  views/img/about.jpg
  views/img/bg1.jpg
  views/img/bg2.jpg
  views/img/bg3.jpg
  views/img/founder.jpeg
  views/img/header.jpg
  views/img/kegiatan1.jpg
  views/img/kegiatan10.jpg
  views/img/kegiatan11.jpg
  views/img/kegiatan12.jpg
  views/img/kegiatan13.jpg
  views/img/kegiatan14.jpg
  views/img/kegiatan15.jpg
  views/img/kegiatan16.jpg
  views/img/kegiatan17.jpg
  views/img/kegiatan2.jpg
  views/img/kegiatan3.jpg
  views/img/kegiatan4.jpg
  views/img/kegiatan5.jpg
  views/img/kegiatan6.jpg
  views/img/kegiatan7.jpg
  views/img/kegiatan8.jpg
  views/img/kegiatan9.jpg
  views/img/logo.jpg
  views/img/logo.png
  views/img/program.jpg
  views/img/program2.jpg
  views/img/program3.jpg
  views/img/program4.jpg
  views/index.php
  views/js/script.js
  views/kegiatan.php
  views/layout.php
Labels: frontend, backend

#18 Fe29nov24irfan
  tentang.html
  tentang.php
  views/css/styles.css
  views/kegiatan.php
  views/layout.php
  views/tentang.php
Labels: frontend

#19 Be29nov24irfan
  .gitignore
  admin/transaksi.php
  admin/views/modalform.js
  admin/views/transaksi.php
  admin/views/users.php
  donasi.php
  konfirmasi.php
  models/model.php
  models/transaksi.php
  views/donasi.php
  views/konfirmasi.php
  views/layout.php
Labels: backend
